---
changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - skip-changelog
      - wont-fix
      - wontfix

  categories:
    - title: Breaking Changes 🛠
      labels:
        - backwards-incompatible

    - title: New Features 🎉
      labels:
        - enhancement

    - title: Bug Fixes 🐛
      labels:
        - bug

    - title: Documentation Updates 📚
      labels:
        - documentation
        - docs

    - title: Container Updates 🐳
      labels:
        - container

    - title: CI/CD Updates 🚀
      labels:
        - ci

    - title: Dependency Updates ⬆️
      labels:
        - dependencies

    - title: Other Changes
      labels:
        - "*"
